### PR TITLE
improvements in the process to create the module tables

### PR DESCRIPTION
**Pull request by leofreitas**
In the current version the table `meetTheTeacherLogin` is not created because it has the same index of the table `meetTheTeacherCustomGroups` in the array $moduleTables. Also I adjusted the charset of tables.

### CODE REVIEW

**Comment by SKuipers** [comment]
Well caught! Looks good. I think utf8_general_ci tends to be the default for the Gibbon core, but as an additional module it may be a non-issue.

@rossdotparker thoughts? merge? 😃

**Comment by rossdotparker** [comment]
Hi Leo, thanks for the contribution.

We are still using utf8 across the core, so not sure it is worth just changing here. It might be worth changing throughout tho. What are the advantages? Emoji support?!

Changing manifest.php is good for new installs, but existing installs also need entries in CHANGEDB.php, which means a new version, which means also incrementing the version in manifest.php and version.php, as well as updating CHANGELOG.txt. This might help next time you are looking at module changes.

Sorry for the slow reply!

Ross

**Comment by leofreitas** [comment]
Hi Ross,
Should I create a new pull request with the requested changes?

**Comment by rossdotparker** [comment]
Hi Leo, you can either add those changes to this request, or create another new request. Up to you. Thanks : )

**Comment by leofreitas** [comment]
Also I returned the charset of the tables for the utf8

**Comment by rossdotparker** [comment]
Hi Leo, sorry, we got out of sync here! I just released a v1.1.01 that had a different feature. Any chance you can bump yours up to v1.1.02, based on the changes in the latest release (to avoid conflicts)? Sorry!

**Comment by leofreitas** [comment]
Hi Ross, no problems! I merge the changes.

**Comment by rossdotparker** [comment]
Thanks for this fix. It is now merged, and I will do the release via GitHub and then share on the Extend page.

**Pull request merged**
